apiVersion: v1
kind: PersistentVolume
metadata:
  name: cyborg-results
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.48.50
    path: "/exports/results/"
